
ubuntu@mtk-genio:~/Desktop/test$ python3 benchmark2.py --file /home/ubuntu/Desktop/test/yolov5x.tflite --target mdla2.0 --count 100
^XTraceback (most recent call last):
  File "/home/ubuntu/Desktop/test/benchmark2.py", line 197, in <module>
    benchmark_tflite_model(args.file, args.target, args.count, compile_options, False, args.profile)
  File "/home/ubuntu/Desktop/test/benchmark2.py", line 96, in benchmark_tflite_model
    tflite_2_dla(model, target, dla, compile_options)
  File "/home/ubuntu/Desktop/test/benchmark2.py", line 90, in tflite_2_dla
    res = subprocess.run(batcmd, shell=True, check=True, executable='/bin/bash', stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ncc-tflite -arch mdla2.0 /home/ubuntu/Desktop/test/yolov5x.tflite -o /home/ubuntu/Desktop/test/yolov5x-mdla2.0.dla  --relax-fp32 ' returned non-zero exit status 1.

----------------------------------

import tensorflow as tf

# Load the YOLOv5x model
converter = tf.lite.TFLiteConverter.from_saved_model('path_to_yolov5x_model')

# Enable integer quantization
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

# Convert the model
tflite_quant_model = converter.convert()

# Save the quantized model
with open('yolov5x_quantized.tflite', 'wb') as f:
    f.write(tflite_quant_model)


python3 benchmark2.py --file /path/to/yolov5x_quantized.tflite --target mdla2.0 --count 100

------------------------------------

ubuntu@mtk-genio:~/Desktop/test$ python3 quantized_model.py 
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/test/quantized_model.py", line 4, in <module>
    converter = tf.lite.TFLiteConverter.from_saved_model('/home/ubuntu/Desktop/test/yolov5x.tflite')
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 2073, in from_saved_model
    saved_model = _load(saved_model_dir, tags)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 900, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 1005, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/loader_impl.py", line 59, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: /home/ubuntu/Desktop/test/yolov5x.tflite/{saved_model.pbtxt|saved_model.pb}
